<?php
    session_start();
	$rand=mt_rand(1000,9999);
	$_SESSION["rand"]=$rand;
	$im=imageCreateTrueColor(75,32);
	$c=imageColorAllocate($im,255,255,255);
	imageTtfText($im,15,-10,10,20,$c,"fonts/verdana.ttf",$rand);
	header("Content-type:image/png");
	imagePng($im);
	imageDestroy($im);
?>